### ISSUE TITLE
setup.py enforces acme<0.40,>=0.39

### ISSUE THREAD

**Issue by flokli** [zenhack/simp_le#131]
I tried bumping `acme` to the latest release (1.0.0), but realized `simp_le` still has much stricter version bounds. Can these be lifted?

@zenhack Similar issue as https://github.com/zenhack/simp_le/issues/35

**Comment by zenhack** [comment]
Hey @flokli,

Sure, we usually bump it with each `simp_le` release, but because we release every 2 months or so and acme has historically done one release a month, we're often two versions behind.

With a version bump to 1.0 we won't need to restrict the version bounds so tightly, but 0.x typically means no compatibility guarantees, and we've dealt with a few api breakages in the past (I got a bug report once about cert revocation being broken, which we tracked down to the reporter's distro having patched out the version bound and used simp_le with an incompatible version of acme...).

We probably ought to have version bounds on more of our dependencies, but the rest of the libraries have been stable enough that it hasn't been a problem.

It's about time for another release; I'll make sure to bump the version when I do that as always (Though usually @buchdag beats me to it :P).
