### ISSUE TITLE
IndexError: list index out of range when using BuyPass ACME

### ISSUE THREAD

**Issue by kradalby** [zenhack/simp_le#133]
Hi

I attempted to use BuyPass as my ACME provider through this docker project https://github.com/jwilder/docker-letsencrypt-nginx-proxy-companion.

But I keep getting this:
```
  2020-01-02 15:19:30,688:INFO:simp_le:1414: Generating new certificate private key
  Traceback (most recent call last):
    File "/usr/lib/python3.7/site-packages/simp_le.py", line 1565, in main
      return main_with_exceptions(cli_args)
    File "/usr/lib/python3.7/site-packages/simp_le.py", line 1549, in main_with_exceptions
      persist_new_data(args, existing_data)
    File "/usr/lib/python3.7/site-packages/simp_le.py", line 1451, in persist_new_data
      OpenSSL.crypto.FILETYPE_PEM, pems[0])),
  IndexError: list index out of range
```

The documentation and ACME URL for BuyPass is provided here:
https://community.buypass.com/t/k9r5cx/get-started

Any idea why this might happen?

**Comment by zenhack** [comment]
Sorry for the slow reply on this. Can you share the arguments you're passing to simp_le, and also a full log having passed `--verbose`?

**Comment by OscarKolsrud** [comment]
Hi there,

Also facing this issue. See this issue for an error log: https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/issues/634

**Comment by OscarKolsrud** [comment]
@zenhack Is my error log sufficent, or do you need any additional information to troubleshoot the issue?

**Comment by zenhack** [comment]
@OscarKolsrud, would you be willing to share that log with the certs not censored? It looks like the issue is that it's somehow not parsing that correctly, so having those removed from the log makes it hard to debug. (If it says "certificate" it's the public part of the cert, so not sensitive, but if you want to avoid sharing it with the whole world anyway, you can email me, address in the commit logs).

**Comment by OscarKolsrud** [comment]
@zenhack Working on sending those over now via email.... Expect them from the email oscar @ <domain on github profile>. If you have an over aggresive mail filter they may end up in spam since i had an IP change.

Sending over the logs of a completely new instance of the docker nginx lets encrypt companion using buypass as CA

**Comment by buchdag** [comment]
@zenhack I might be able to help if @OscarKolsrud is ok about sharing the cert with me too.

**Comment by OscarKolsrud** [comment]
@buchdag Check your gmail (the one listed in your github profile)

**Comment by OscarKolsrud** [comment]
Can confirm oull request https://github.com/zenhack/simp_le/pull/137 solved this issue

**Comment by zenhack** [comment]
Ok, the fix is on master. I'll try to get a release out soonish.

**Comment by buchdag** [comment]
@zenhack could you try to release the fixed version as soon as convenient for you ? It can't go into `letsencrypt-nginx-proxy-companion` if this isn't a tagged release.

**Comment by zenhack** [comment]
Done.
