### ISSUE TITLE
Exit code on Python crash

### ISSUE THREAD

**Issue by VojtechMyslivec** [zenhack/simp_le#54]
Due to [manifesto](../blob/master/README.rst#manifesto), exit code `1` is reserved for "renewal not necessary".

In last month, `simp_le` keeps failing for some reason and returns `1` so my wrapper script do nothing, because certificate looks up-to-date. Everything was fixed when I upgrade `simp_le` but my certificates expired without any reported errors.

Please catch all exceptions and return non-one non-zero error code, when something went wrong and exception is thrown. [Here](https://github.com/zenhack/simp_le/files/1067781/simp_le.txt) is some log from `simp_le`, if it helps.

**Comment by zenhack** [comment]
Thanks for the bug report, and I'm sorry this happened.

We actually *do* have a catch-all in place like you suggest, but the
error from that text file looks like it's being thrown by python
machinery before simp_le even gets called. It's indicative of some kind
of installation problem, so it's unsurprising that upgrading fixed it.

Unfortunately this means it's not actually possible to change the exit
status for this sort of problem. Maybe the correct approach is to change
the way we use the status, so that real errors from simp_le agree with
things python does (i.e. use 1 for errors, something else for no renewal
necessary).  This would break existing scripts though, so I'm somewhat
hesitant. But the failure mode you describe is definitely worth
trying to prevent. Thoughts?

Thanks again for reporting this.

**Comment by VojtechMyslivec** [comment]
Ahhh I see, thanks for explanation – bad luck for me. It is really strange case then and I believe it won't happen too often.

Changing exit codes is really big step. If I am only one reporting this kind of problem just let it as is for now. In other case is maybe possible to create some backward-incompatible version in separate branch?

Thank you for maintaining this tool.

**Comment by zenhack** [comment]
Yeah, the big hitch is how to communicate the breakage to users -- I don't think I really have the ability to do that easily. I'm going to close this, if I come up with a solution I may re-open/fix.

and you're welcome, and sorry again :(

**Comment by zenhack** [comment]
Maybe put in a deprecation notice to the tool itself and leave it there for a while before making the change, which will be done on a specific version boundary. But I"m going to close, not going to do anything until I'm comfortable.
