### ISSUE TITLE
Alternative chain paths

### ISSUE THREAD

**Issue by VojtechMyslivec** [zenhack/simp_le#68]
Thank you for maintaining `simp_le` tool.

I have a question about alternative chains for issued certificates, which are described in [Chain of Trust](https://letsencrypt.org/certificates/#cross-signing)

I use `simp_le` with `-f fullchain.pem` parameter and it saves 2 certs in the file:
```
Certificate chain
 0 s:/CN=example.org
   i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
 1 s:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
   i:/O=Digital Signature Trust Co./CN=DST Root CA X3
```

Which is correct and trusted with IdenTrust *DST Root CA X3*. But if I look on Let's Encrypt [demo webpage](https://valid-isrgrootx1.letsencrypt.org/), it sends following chain:
```
Certificate chain
 0 s:/CN=valid-isrgrootx1.letsencrypt.org
   i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
 1 s:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
   i:/C=US/O=Internet Security Research Group/CN=ISRG Root X1
```

So my question is why *simp_le* generates chain with *DST Root CA X3* and *demo* page is with *ISRG Root X1*? Is there some way to generate chain with both alternative paths?

**Comment by zenhack** [comment]
Sorry for the slow response on this one.

I don't know off-hand what simp_le is doing differently; I'll try to find time in the next week to sit down and figure it out (but I wanted to at least respond in the meantime, rather than just not acknowledging the issue).

**Comment by buchdag** [comment]
I don't think simp_le does things differently than certbot, I have certificates created by both and they  both have the same chain : mydomain.tld > Let's Encrypt Authority X3 > DST Root CA X3 (as does [Let's Encrypt community board](https://www.ssllabs.com/ssltest/analyze.html?d=community.letsencrypt.org&s=2001%3a470%3a1%3a3a8%3a0%3a0%3a0%3a201&latest)).

[The demo page you linked is providing two chains](https://www.ssllabs.com/ssltest/analyze.html?d=valid-isrgrootx1.letsencrypt.org), the one that seems to be provided by default by simp_le or certbot and the second one with ISRG Root X1. I don't think there is an option in certbot to get that chain instead of the one that is cross signed by DST Root CA X3.

**Comment by VojtechMyslivec** [comment]
Thanks for reply and for the links. I have found only the one with *ISRG Root X1*. It seems that *DST Root X3* is the standard one.

@buchdag I don't think that the page offer 2 alternative chains (see `openssl` output from my post) but *ssllabs* just found the alternate one with "extra"-downloaded intermediate cert.

**Comment by zenhack** [comment]
@buchdag thanks for investigating this.
